name: Cloudflare Deployment
description: Deploys to Cloudflare
inputs:
  project-name:
    description: Name of Cloudflare project to deploy to
    required: true
outputs:
  url:
    description: URL of deployed Cloudflare site
    value: ${{ steps.deployment.outputs.url }}

runs:
    using: composite
    steps:
      # workaround documented here: https://github.com/cloudflare/workers-sdk/issues/3615
      - run: npm i -d wrangler
      - run: sed '/"\*\*\/node_modules",/d' cli.js > cliv2.js
        working-directory: node_modules/wrangler/wrangler-dist
      - run: diff cli.js cliv2.js || true
        working-directory: node_modules/wrangler/wrangler-dist
      - run: mv -f cliv2.js cli.js
        working-directory: node_modules/wrangler/wrangler-dist
      - run: npm run build:metro-web
      - name: Cloudflare Deployment
        id: deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ inputs.project-name }}
          directory: dist