default_stages: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        entry: npx lint-staged
        always_run: true
        language: system
        verbose: false