name: Set Changelog Date
description: Sets changelog date in changelog.json

runs:
  using: composite
  steps:
    - name: Install script dependencies
      shell: bash
      working-directory: .github/scripts
      run: npm i
    - name: Update Changelog Date
      shell: bash
      run: npx bun ./.github/scripts/set-changelog-date.js