name: Deploy site to Cloudflare
description: Deploys web bundle to Cloudflare Pages
inputs:
  project-name:
    description: Name of Cloudflare project to deploy to
    required: true
  account-id:
    description: Cloudflare account id
    required: true
  api-token:
    description: Cloudflare API token
    required: true
outputs:
  url:
    description: URL of deployed Cloudflare site
    value: ${{ steps.deployment.outputs.deployment-url }}

runs:
  using: composite
  steps:
    # workaround documented here: https://github.com/cloudflare/workers-sdk/issues/3615
    - run: npm i -d wrangler
      shell: bash
    - run: sed '/"\*\*\/node_modules",/d' cli.js > cliv2.js
      working-directory: node_modules/wrangler/wrangler-dist
      shell: bash
    - run: diff cli.js cliv2.js || true
      working-directory: node_modules/wrangler/wrangler-dist
      shell: bash
    - run: mv -f cliv2.js cli.js
      working-directory: node_modules/wrangler/wrangler-dist
      shell: bash
    - run: npm run build:metro-web
      shell: bash
    - name: Cloudflare Deployment
      id: deployment
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.api-token }}
        accountId: ${{ inputs.account-id }}
        command: pages deploy sudokuru/dist --project-name=${{ inputs.project-name }}