name: "Pipeline"

on:
  push:
    # It is easier to list paths to exclude rather than paths to include
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "license.md"
    branches:
      - main
  pull_request:
    # It is easier to list paths to exclude rather than paths to include
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "license.md"
    branches:
      - main

# https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
# A PR will have workflows in the same group, different PRs will have workflows in different groups, and each main workflow will have different group IDs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  code_scan:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: Prettier Check
        run: |
          npm i prettier@2.8.8
          npx prettier --check .

  app_preview_dev:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [ code_scan ]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci && npx expo install expo-updates

      - name: 🚀 Publish App preview
        run: USERGAMESTATISTICSBFFURL=${{ secrets.DEV_USERGAMESTATISTICSBFFURL }} USERACTIVEGAMESBFFURL=${{ secrets.DEV_USERACTIVEGAMESBFFURL }} DOMAIN=${{ secrets.DEV_DOMAIN }} CLIENT_ID=${{ secrets.DEV_CLIENT_ID }} AUDIENCE=${{ secrets.DEV_AUDIENCE }} SCOPE=${{ secrets.DEV_SCOPE }} expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: Publish Website Preview
        run: echo "previewUrl=$(npx vercel --yes --name sudokuru-dev --token ${{secrets.VERCEL_TOKEN}})" >> $GITHUB_ENV

      - name: Post comment with preview link
        uses: KeisukeYamashita/create-comment@v1
        with:
          check-only-first-line: true
          comment: |
            Preview App for PR:
            https://expo.dev/@sudokuru/sudokuru?serviceType=classic&distribution=expo-go&release-channel=pr-${{ github.event.number }}
            Preview Website for PR:
            ${{ env.previewUrl }}

  website_test_dev:
    runs-on: ubuntu-latest
    needs: [ code_scan ]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run web
          wait-on: 'http://localhost:19000/'
          wait-on-timeout: 120

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: ./cypress/videos

  app_build_dev:
    runs-on: ubuntu-latest
    needs: [ code_scan ]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Build app
        run: USERGAMESTATISTICSBFFURL=${{ secrets.DEV_USERGAMESTATISTICSBFFURL }} USERACTIVEGAMESBFFURL=${{ secrets.DEV_USERACTIVEGAMESBFFURL }} DOMAIN=${{ secrets.DEV_DOMAIN }} CLIENT_ID=${{ secrets.DEV_CLIENT_ID }} AUDIENCE=${{ secrets.DEV_AUDIENCE }} SCOPE=${{ secrets.DEV_SCOPE }} eas build --non-interactive --platform android --local
        env:
          EAS_LOCAL_BUILD_ARTIFACTS_DIR: BuildDev

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android Dev APK
          path: BuildDev/*.apk

  app_build_prod:
    runs-on: ubuntu-latest
    needs: [ code_scan, website_test_dev ]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Build app
        run: USERGAMESTATISTICSBFFURL=${{ secrets.PROD_USERGAMESTATISTICSBFFURL }} USERACTIVEGAMESBFFURL=${{ secrets.PROD_USERACTIVEGAMESBFFURL }} DOMAIN=${{ secrets.PROD_DOMAIN }} CLIENT_ID=${{ secrets.PROD_CLIENT_ID }} AUDIENCE=${{ secrets.PROD_AUDIENCE }} SCOPE=${{ secrets.PROD_SCOPE }} eas build --non-interactive --platform android --local
        env:
          EAS_LOCAL_BUILD_ARTIFACTS_DIR: BuildProd

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android Prod APK
          path: BuildProd/*.apk

  deploy_app_dev:
    name: Deploy Dev app to Itch.io
    needs: [ app_build_dev, website_test_dev ]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: Android Dev APK

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Update Itch.io Android Alpha App
        run: ./butler push . ${{secrets.ITCH_USERNAME}}/${{secrets.ITCH_GAME_ID}}:alpha-android
        env:
          BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}

  deploy_app_prod:
    name: Deploy Prod app to Itch.io
    needs: [ app_build_prod ]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: Android Prod APK

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Update Itch.io Android Prod App
        run: ./butler push . ${{secrets.ITCH_USERNAME}}/${{secrets.ITCH_GAME_ID}}:stable-android
        env:
          BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}

  deploy_website_dev:
    name: Deploy Dev Website
    needs: [ app_build_dev, website_test_dev ]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: npm ci

      - run: npx vercel --yes --prod --name sudokuru-dev --token ${{secrets.VERCEL_TOKEN}}

  deploy_website_prod:
    name: Deploy Prod Website
    needs: [ app_build_prod ]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: npm ci

      - run: npx vercel --yes --prod --name sudokuru --token ${{secrets.VERCEL_TOKEN}}
